# # Written for Mac OSX - 10.7.4

# asian: main.cpp asian.o payoff.o
# 	clang++ -o asian main.cpp asian.o payoff.o -arch x86_64

# asian.o: asian.cpp payoff.o
# 	clang++ -c asian.cpp payoff.o -arch x86_64 

# payoff.o: payoff.cpp
# 	clang++ -c payoff.cpp -arch x86_64




asian: main.cpp asian.o payoff.o
	g++ -o asian main.cpp asian.o payoff.o

asian.o: asian.cpp payoff.o
	g++ -c asian.cpp payoff.o 

payoff.o: payoff.cpp
	g++ -c payoff.cpp
